package nl.lunatech.util

enum class Topic(val topic: String) {
    BROKEN_CAR_TOPIC("BROKEN_CAR_TOPIC"),
    NEW_CAR_WITH_PROBLEM_ADDED_TOPIC("NEW_CAR_WITH_PROBLEM_ADDED_TOPIC"),
    CAR_ADDED_TO_PROBLEMS_TOPIC("CAR_ADDED_TO_PROBLEMS_TOPIC")
    ;
}
